runtime: python312

handlers:

  - url: /static/
    static_dir: static
    secure: always
    http_headers:
      Strict-Transport-Security: "max-age=2592000; includeSubdomains"
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"

  - url: /.*
    script: auto
    secure: always

env_variables:
  FLASK_SETTINGS_FILENAME: "settings.py"
